inherits: products.yml

dimensions: 
- alias: ext
  values: ["zip", "xlsx", "xlt", "xltm", "xltx", "vss", "vsx", "wav", "webp", "wmf", "xls", "xlsb", "xlsm", "torrent", "ttf", "vcf", "vdx", "vsd", "vsdx", "vcr", "ppsm", "ppsx", "ppt", "pptm", "pptx", "psd", "tif", "tiff", "one", "otf", "pdf", "png", "pot", "potm", "potx", "pps", "mov", "mp3", "mpp", "mpt", "msg", "ods", "odt", "heif", "jp2", "jpeg", "jpf", "jpg", "mkv", "dwg", "dxf", "emf", "eml", "epub", "flv", "gif", "heic", "dcm", "dicom", "djvu", "doc", "docm", "docx", "dot", "dotm", "dotx", "asf", "avi", "bmp", "zip", "xlsb", "xlsm", "xlt", "xltm", "xltx", "xlsx", "vss", "vsx", "wav", "xls", "webp", "wmf", "ttf", "vcf", "vdx", "vsd", "vsdx", "vcr", "torrent", "pps", "ppsm", "ppsx", "ppt", "pptm", "pptx", "psd", "tif", "tiff", "png", "pot", "potm", "potx", "otf", "pdf", "one", "mov", "mpp", "mpt", "ods", "odt", "mp3", "msg", "jpeg", "jpg", "heic", "heif", "jp2", "jpf", "mkv", "dwg", "dxf", "emf", "eml", "flv", "gif", "epub", "djvu", "docm", "dot", "dotm", "dotx", "doc", "docx", "otc", "asf", "bmp", "dcm", "dicom", "avi"]

generationRules:
  exclude:
##    - ext[excel, image, onenote, visio, web, word, worksheet]
  include:
##  - ext[odt]

dictionaries: [ "..\\data\\edit_{product}.{lang}.json", "..\\data\\edit_{product}.json", "..\\data\\otherformats.json" ]

outputPath: "{product}\\edit\\{ext}.{lang}.md"