::call translate_json index_net ru
::call translate_json index_net bg
::call translate_json index_net de
::call translate_json index_net es
::call translate_json index_net fr
::call translate_json index_net id
::call translate_json index_net it
::call translate_json index_net ja
::call translate_json index_net ko
::call translate_json index_net pl
::call translate_json index_net pt
::call translate_json index_net th
::call translate_json index_net tr
::call translate_json index_net vi
::call translate_json index_net zh-cn