call translate_json index ru
::call translate_json index bg
::call translate_json index de
::call translate_json index es
::call translate_json index fr
::call translate_json index id
::call translate_json index it
::call translate_json index ja
::call translate_json index ko
::call translate_json index pl
::call translate_json index pt
::call translate_json index th
::call translate_json index tr
::call translate_json index vi
::call translate_json index zh-cn
